### ISSUE TITLE
Data migration script from kvalobs and KDVH

### ISSUE THREAD

**Issue by intarga** [metno/lard#14]

**Comment by lcoram** [comment]
https://gitlab.met.no/oda/oda/-/blob/main/tools/kdvh-importer/dataandflags.go?ref_type=heads#L105
If we look inside each of the CustomDataFunction: sections for this list of tables, you could hopefully take the information that is currently being wrapped in a oda.timeseriesdata at the end of the function and insert it appropriately into the data and flags tables.
